### ISSUE TITLE
Cordova - TypeError: 'Converting circular structure to JSON'

### ISSUE THREAD

**Issue by freshdev1** [Azure/azure-mobile-apps-js-client#201]
Hello Everybody. I have been following this example:
https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples

I copied the following lines:
https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/master/offline-sync-error-handling/www/js/tableManager.js#L64-L66

but when I run, I get the following in the console:
`TypeError: 'Converting circular structure to JSON'`

Some details that can be of interest for the devs. Exception is caught at line number 45388 of the MobileServices.Cordova.js

**Stack Trace:**

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at makeCopy (file:///android_asset/www/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:45862:34)
    at Object.getError (file:///android_asset/www/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:45609:16)
    at ComparePage.OnConflict (file:///android_asset/www/build/js/app.bundle.js:166:50)
    at Object.CreateAzureClient.then._this._syncContext.initialize.then._this._syncContext.pushHandler.onConflict (file:///android_asset/www/build/js/app.bundle.js:133:73)
    at file:///android_asset/www/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:45878:36
    at Promise.<anonymous> (file:///android_asset/www/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:43585:40)
    at file:///android_asset/www/plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js:43529:68
    at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/zone.js:356:38)
    at Zone.runTask (file:///android_asset/www/build/js/zone.js:256:48)
```

Actual call which is resulting in a conflict:
`PATCH http://10.0.3.2:8090/SomeAzureMobileServices/tables/Issue/6c10a54a-c1eb-44b4-acfd-459e653ed9bc 409 (Conflict)`

If any other details are required, feel free  to ask me that.

**Comment by shrishrirang** [comment]
Can you check which member is causing the circular dependency? I am guessing it is either the `request` or `response` property. Also, are you using a node backend or a .net backend?

**Comment by rob3c** [comment]
Wow, I was just reading through the source and wondered if someone would be hitting that error! :-) It happens because the internal `makeCopy` function just uses `JSON.stringify` then `JSON.parse` to copy objects (from the stack trace above, an error object in this case), and that has the associated stringify problems with circular dependencies.

**Comment by freshdev1** [comment]
@shrishrirang I tried to check that, but was not able to identify that. I believe the error is caused by `response` property. And I am using .NET Backend.

**Comment by shrishrirang** [comment]
Right, it's `JSON.stringify` that's the culprit here. I didn't expect `request` / `response` to have any loops - bad assumption :(

**Comment by shrishrirang** [comment]
Closed by https://github.com/Azure/azure-mobile-apps-js-client/pull/230
